// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry/uptimer/cfWorkflow"
	"github.com/cloudfoundry/uptimer/cmdRunner"
)

type FakeCfWorkflow struct {
	SetupStub        func() []cmdRunner.CmdStartWaiter
	setupMutex       sync.RWMutex
	setupArgsForCall []struct{}
	setupReturns     struct {
		result1 []cmdRunner.CmdStartWaiter
	}
	TearDownStub        func() []cmdRunner.CmdStartWaiter
	tearDownMutex       sync.RWMutex
	tearDownArgsForCall []struct{}
	tearDownReturns     struct {
		result1 []cmdRunner.CmdStartWaiter
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCfWorkflow) Setup() []cmdRunner.CmdStartWaiter {
	fake.setupMutex.Lock()
	fake.setupArgsForCall = append(fake.setupArgsForCall, struct{}{})
	fake.recordInvocation("Setup", []interface{}{})
	fake.setupMutex.Unlock()
	if fake.SetupStub != nil {
		return fake.SetupStub()
	} else {
		return fake.setupReturns.result1
	}
}

func (fake *FakeCfWorkflow) SetupCallCount() int {
	fake.setupMutex.RLock()
	defer fake.setupMutex.RUnlock()
	return len(fake.setupArgsForCall)
}

func (fake *FakeCfWorkflow) SetupReturns(result1 []cmdRunner.CmdStartWaiter) {
	fake.SetupStub = nil
	fake.setupReturns = struct {
		result1 []cmdRunner.CmdStartWaiter
	}{result1}
}

func (fake *FakeCfWorkflow) TearDown() []cmdRunner.CmdStartWaiter {
	fake.tearDownMutex.Lock()
	fake.tearDownArgsForCall = append(fake.tearDownArgsForCall, struct{}{})
	fake.recordInvocation("TearDown", []interface{}{})
	fake.tearDownMutex.Unlock()
	if fake.TearDownStub != nil {
		return fake.TearDownStub()
	} else {
		return fake.tearDownReturns.result1
	}
}

func (fake *FakeCfWorkflow) TearDownCallCount() int {
	fake.tearDownMutex.RLock()
	defer fake.tearDownMutex.RUnlock()
	return len(fake.tearDownArgsForCall)
}

func (fake *FakeCfWorkflow) TearDownReturns(result1 []cmdRunner.CmdStartWaiter) {
	fake.TearDownStub = nil
	fake.tearDownReturns = struct {
		result1 []cmdRunner.CmdStartWaiter
	}{result1}
}

func (fake *FakeCfWorkflow) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.setupMutex.RLock()
	defer fake.setupMutex.RUnlock()
	fake.tearDownMutex.RLock()
	defer fake.tearDownMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeCfWorkflow) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cfWorkflow.CfWorkflow = new(FakeCfWorkflow)
