// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/cloudfoundry/uptimer/cmdRunner"
	"github.com/cloudfoundry/uptimer/cmdStartWaiter"
)

type FakeCmdRunner struct {
	RunStub        func(cmdStartWaiter cmdStartWaiter.CmdStartWaiter) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		cmdStartWaiter cmdStartWaiter.CmdStartWaiter
	}
	runReturns struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	RunInSequenceStub        func(cmdStartWaiters ...cmdStartWaiter.CmdStartWaiter) error
	runInSequenceMutex       sync.RWMutex
	runInSequenceArgsForCall []struct {
		cmdStartWaiters []cmdStartWaiter.CmdStartWaiter
	}
	runInSequenceReturns struct {
		result1 error
	}
	runInSequenceReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCmdRunner) Run(csw cmdStartWaiter.CmdStartWaiter) error {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		cmdStartWaiter cmdStartWaiter.CmdStartWaiter
	}{csw})
	fake.recordInvocation("Run", []interface{}{csw})
	fake.runMutex.Unlock()
	if fake.RunStub != nil {
		return fake.RunStub(csw)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.runReturns.result1
}

func (fake *FakeCmdRunner) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeCmdRunner) RunArgsForCall(i int) cmdStartWaiter.CmdStartWaiter {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.runArgsForCall[i].cmdStartWaiter
}

func (fake *FakeCmdRunner) RunReturns(result1 error) {
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCmdRunner) RunReturnsOnCall(i int, result1 error) {
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCmdRunner) RunInSequence(cmdStartWaiters ...cmdStartWaiter.CmdStartWaiter) error {
	fake.runInSequenceMutex.Lock()
	ret, specificReturn := fake.runInSequenceReturnsOnCall[len(fake.runInSequenceArgsForCall)]
	fake.runInSequenceArgsForCall = append(fake.runInSequenceArgsForCall, struct {
		cmdStartWaiters []cmdStartWaiter.CmdStartWaiter
	}{cmdStartWaiters})
	fake.recordInvocation("RunInSequence", []interface{}{cmdStartWaiters})
	fake.runInSequenceMutex.Unlock()
	if fake.RunInSequenceStub != nil {
		return fake.RunInSequenceStub(cmdStartWaiters...)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.runInSequenceReturns.result1
}

func (fake *FakeCmdRunner) RunInSequenceCallCount() int {
	fake.runInSequenceMutex.RLock()
	defer fake.runInSequenceMutex.RUnlock()
	return len(fake.runInSequenceArgsForCall)
}

func (fake *FakeCmdRunner) RunInSequenceArgsForCall(i int) []cmdStartWaiter.CmdStartWaiter {
	fake.runInSequenceMutex.RLock()
	defer fake.runInSequenceMutex.RUnlock()
	return fake.runInSequenceArgsForCall[i].cmdStartWaiters
}

func (fake *FakeCmdRunner) RunInSequenceReturns(result1 error) {
	fake.RunInSequenceStub = nil
	fake.runInSequenceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCmdRunner) RunInSequenceReturnsOnCall(i int, result1 error) {
	fake.RunInSequenceStub = nil
	if fake.runInSequenceReturnsOnCall == nil {
		fake.runInSequenceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runInSequenceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCmdRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	fake.runInSequenceMutex.RLock()
	defer fake.runInSequenceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCmdRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cmdRunner.CmdRunner = new(FakeCmdRunner)
