resources:
- name: uptimer
  type: git
  icon: github
  source:
    uri: https://github.com/cloudfoundry/uptimer.git
    branch: main

- name: runtime-ci
  type: git
  icon: github
  source:
    branch: main
    uri: https://github.com/cloudfoundry/runtime-ci.git

jobs:
- name: run-unit-tests
  public: true
  plan:
  - get: uptimer
    trigger: true
  - get: runtime-ci
  - task: run-unit-tests
    file: runtime-ci/tasks/run-uptimer-unit-tests/task.yml
