// Code generated by counterfeiter. DO NOT EDIT.
package measurementfakes

import (
	"sync"

	"github.com/cloudfoundry/uptimer/measurement"
)

type FakeMeasurement struct {
	FailedStub        func() bool
	failedMutex       sync.RWMutex
	failedArgsForCall []struct {
	}
	failedReturns struct {
		result1 bool
	}
	failedReturnsOnCall map[int]struct {
		result1 bool
	}
	NameStub        func() string
	nameMutex       sync.RWMutex
	nameArgsForCall []struct {
	}
	nameReturns struct {
		result1 string
	}
	nameReturnsOnCall map[int]struct {
		result1 string
	}
	ResultsStub        func() measurement.ResultSet
	resultsMutex       sync.RWMutex
	resultsArgsForCall []struct {
	}
	resultsReturns struct {
		result1 measurement.ResultSet
	}
	resultsReturnsOnCall map[int]struct {
		result1 measurement.ResultSet
	}
	StartStub        func()
	startMutex       sync.RWMutex
	startArgsForCall []struct {
	}
	StopStub        func()
	stopMutex       sync.RWMutex
	stopArgsForCall []struct {
	}
	SummaryStub        func() string
	summaryMutex       sync.RWMutex
	summaryArgsForCall []struct {
	}
	summaryReturns struct {
		result1 string
	}
	summaryReturnsOnCall map[int]struct {
		result1 string
	}
	SummaryDataStub        func() measurement.Summary
	summaryDataMutex       sync.RWMutex
	summaryDataArgsForCall []struct {
	}
	summaryDataReturns struct {
		result1 measurement.Summary
	}
	summaryDataReturnsOnCall map[int]struct {
		result1 measurement.Summary
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMeasurement) Failed() bool {
	fake.failedMutex.Lock()
	ret, specificReturn := fake.failedReturnsOnCall[len(fake.failedArgsForCall)]
	fake.failedArgsForCall = append(fake.failedArgsForCall, struct {
	}{})
	stub := fake.FailedStub
	fakeReturns := fake.failedReturns
	fake.recordInvocation("Failed", []interface{}{})
	fake.failedMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMeasurement) FailedCallCount() int {
	fake.failedMutex.RLock()
	defer fake.failedMutex.RUnlock()
	return len(fake.failedArgsForCall)
}

func (fake *FakeMeasurement) FailedCalls(stub func() bool) {
	fake.failedMutex.Lock()
	defer fake.failedMutex.Unlock()
	fake.FailedStub = stub
}

func (fake *FakeMeasurement) FailedReturns(result1 bool) {
	fake.failedMutex.Lock()
	defer fake.failedMutex.Unlock()
	fake.FailedStub = nil
	fake.failedReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeMeasurement) FailedReturnsOnCall(i int, result1 bool) {
	fake.failedMutex.Lock()
	defer fake.failedMutex.Unlock()
	fake.FailedStub = nil
	if fake.failedReturnsOnCall == nil {
		fake.failedReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.failedReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeMeasurement) Name() string {
	fake.nameMutex.Lock()
	ret, specificReturn := fake.nameReturnsOnCall[len(fake.nameArgsForCall)]
	fake.nameArgsForCall = append(fake.nameArgsForCall, struct {
	}{})
	stub := fake.NameStub
	fakeReturns := fake.nameReturns
	fake.recordInvocation("Name", []interface{}{})
	fake.nameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMeasurement) NameCallCount() int {
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	return len(fake.nameArgsForCall)
}

func (fake *FakeMeasurement) NameCalls(stub func() string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = stub
}

func (fake *FakeMeasurement) NameReturns(result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	fake.nameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeMeasurement) NameReturnsOnCall(i int, result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	if fake.nameReturnsOnCall == nil {
		fake.nameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.nameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeMeasurement) Results() measurement.ResultSet {
	fake.resultsMutex.Lock()
	ret, specificReturn := fake.resultsReturnsOnCall[len(fake.resultsArgsForCall)]
	fake.resultsArgsForCall = append(fake.resultsArgsForCall, struct {
	}{})
	stub := fake.ResultsStub
	fakeReturns := fake.resultsReturns
	fake.recordInvocation("Results", []interface{}{})
	fake.resultsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMeasurement) ResultsCallCount() int {
	fake.resultsMutex.RLock()
	defer fake.resultsMutex.RUnlock()
	return len(fake.resultsArgsForCall)
}

func (fake *FakeMeasurement) ResultsCalls(stub func() measurement.ResultSet) {
	fake.resultsMutex.Lock()
	defer fake.resultsMutex.Unlock()
	fake.ResultsStub = stub
}

func (fake *FakeMeasurement) ResultsReturns(result1 measurement.ResultSet) {
	fake.resultsMutex.Lock()
	defer fake.resultsMutex.Unlock()
	fake.ResultsStub = nil
	fake.resultsReturns = struct {
		result1 measurement.ResultSet
	}{result1}
}

func (fake *FakeMeasurement) ResultsReturnsOnCall(i int, result1 measurement.ResultSet) {
	fake.resultsMutex.Lock()
	defer fake.resultsMutex.Unlock()
	fake.ResultsStub = nil
	if fake.resultsReturnsOnCall == nil {
		fake.resultsReturnsOnCall = make(map[int]struct {
			result1 measurement.ResultSet
		})
	}
	fake.resultsReturnsOnCall[i] = struct {
		result1 measurement.ResultSet
	}{result1}
}

func (fake *FakeMeasurement) Start() {
	fake.startMutex.Lock()
	fake.startArgsForCall = append(fake.startArgsForCall, struct {
	}{})
	stub := fake.StartStub
	fake.recordInvocation("Start", []interface{}{})
	fake.startMutex.Unlock()
	if stub != nil {
		fake.StartStub()
	}
}

func (fake *FakeMeasurement) StartCallCount() int {
	fake.startMutex.RLock()
	defer fake.startMutex.RUnlock()
	return len(fake.startArgsForCall)
}

func (fake *FakeMeasurement) StartCalls(stub func()) {
	fake.startMutex.Lock()
	defer fake.startMutex.Unlock()
	fake.StartStub = stub
}

func (fake *FakeMeasurement) Stop() {
	fake.stopMutex.Lock()
	fake.stopArgsForCall = append(fake.stopArgsForCall, struct {
	}{})
	stub := fake.StopStub
	fake.recordInvocation("Stop", []interface{}{})
	fake.stopMutex.Unlock()
	if stub != nil {
		fake.StopStub()
	}
}

func (fake *FakeMeasurement) StopCallCount() int {
	fake.stopMutex.RLock()
	defer fake.stopMutex.RUnlock()
	return len(fake.stopArgsForCall)
}

func (fake *FakeMeasurement) StopCalls(stub func()) {
	fake.stopMutex.Lock()
	defer fake.stopMutex.Unlock()
	fake.StopStub = stub
}

func (fake *FakeMeasurement) Summary() string {
	fake.summaryMutex.Lock()
	ret, specificReturn := fake.summaryReturnsOnCall[len(fake.summaryArgsForCall)]
	fake.summaryArgsForCall = append(fake.summaryArgsForCall, struct {
	}{})
	stub := fake.SummaryStub
	fakeReturns := fake.summaryReturns
	fake.recordInvocation("Summary", []interface{}{})
	fake.summaryMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMeasurement) SummaryCallCount() int {
	fake.summaryMutex.RLock()
	defer fake.summaryMutex.RUnlock()
	return len(fake.summaryArgsForCall)
}

func (fake *FakeMeasurement) SummaryCalls(stub func() string) {
	fake.summaryMutex.Lock()
	defer fake.summaryMutex.Unlock()
	fake.SummaryStub = stub
}

func (fake *FakeMeasurement) SummaryReturns(result1 string) {
	fake.summaryMutex.Lock()
	defer fake.summaryMutex.Unlock()
	fake.SummaryStub = nil
	fake.summaryReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeMeasurement) SummaryReturnsOnCall(i int, result1 string) {
	fake.summaryMutex.Lock()
	defer fake.summaryMutex.Unlock()
	fake.SummaryStub = nil
	if fake.summaryReturnsOnCall == nil {
		fake.summaryReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.summaryReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeMeasurement) SummaryData() measurement.Summary {
	fake.summaryDataMutex.Lock()
	ret, specificReturn := fake.summaryDataReturnsOnCall[len(fake.summaryDataArgsForCall)]
	fake.summaryDataArgsForCall = append(fake.summaryDataArgsForCall, struct {
	}{})
	stub := fake.SummaryDataStub
	fakeReturns := fake.summaryDataReturns
	fake.recordInvocation("SummaryData", []interface{}{})
	fake.summaryDataMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMeasurement) SummaryDataCallCount() int {
	fake.summaryDataMutex.RLock()
	defer fake.summaryDataMutex.RUnlock()
	return len(fake.summaryDataArgsForCall)
}

func (fake *FakeMeasurement) SummaryDataCalls(stub func() measurement.Summary) {
	fake.summaryDataMutex.Lock()
	defer fake.summaryDataMutex.Unlock()
	fake.SummaryDataStub = stub
}

func (fake *FakeMeasurement) SummaryDataReturns(result1 measurement.Summary) {
	fake.summaryDataMutex.Lock()
	defer fake.summaryDataMutex.Unlock()
	fake.SummaryDataStub = nil
	fake.summaryDataReturns = struct {
		result1 measurement.Summary
	}{result1}
}

func (fake *FakeMeasurement) SummaryDataReturnsOnCall(i int, result1 measurement.Summary) {
	fake.summaryDataMutex.Lock()
	defer fake.summaryDataMutex.Unlock()
	fake.SummaryDataStub = nil
	if fake.summaryDataReturnsOnCall == nil {
		fake.summaryDataReturnsOnCall = make(map[int]struct {
			result1 measurement.Summary
		})
	}
	fake.summaryDataReturnsOnCall[i] = struct {
		result1 measurement.Summary
	}{result1}
}

func (fake *FakeMeasurement) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.failedMutex.RLock()
	defer fake.failedMutex.RUnlock()
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	fake.resultsMutex.RLock()
	defer fake.resultsMutex.RUnlock()
	fake.startMutex.RLock()
	defer fake.startMutex.RUnlock()
	fake.stopMutex.RLock()
	defer fake.stopMutex.RUnlock()
	fake.summaryMutex.RLock()
	defer fake.summaryMutex.RUnlock()
	fake.summaryDataMutex.RLock()
	defer fake.summaryDataMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMeasurement) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ measurement.Measurement = new(FakeMeasurement)
